repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: bash scripts/format.sh
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: lint
        entry: bash scripts/lint.sh
        language: system
        types: [python]
        pass_filenames: false

      - id: test
        name: test
        entry: bash scripts/test.sh
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]  # Only run tests before pushing
